### Login usuario
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
    
    "email": "test@test.com",
    "password": "123456"
}

### Crear usuario
POST http://127.0.0.1:8000/user
Content-Type: application/json

{
    "nombre": "luis",
    "email": "Lnavarro@gmail.com",
    "password": "123456"
}

### Ver usuarios
GET  http://127.0.0.1:8000/view_user
Content-Type: application/json


### Status 
GET http://127.0.0.1:8000/status
Content-Type: application/json

### Limpiar Puertos de los Switches
POST http://127.0.0.1:8000/limpiar_ports
Accept: application/json


### Limpiar Puertos de los Switches por ip
GET http://127.0.0.1:8000/limpiar_ports/10.20.100.52
Accept: application/json

### Limpiar Puertos de los Switches y Guardar en DB
POST http://127.0.0.1:8000/registrar_ports_db
Content-Type: application/json

{
    "ip": "192.168.1.15",
    "nombre": "Puerto_Switch_01",
    "user_ip": "admin",
    "pass_ip": "secreto123",
    "description": "Limpieza de mantenimiento mensual"
}

### Ver Puertos Limpiados en DB
GET http://127.0.0.1:8000/view_clearports
Content-Type: application/json


### registrar bot
POST http://127.0.0.1:8000/bot/registrar_boot
Content-Type: application/json

{
    "chat_id": "5909631520",
    "token":"8593251070:AAG_nx3e_8fzVQAG3YQD4d_kPxx6lTkX9Ws"
}

###status de reportes
POST http://127.0.0.1:8000/send-test-telegram
Content-Type: application/json

{}

### ELIMINIAR USUARIO
DELETE  http://127.0.0.1:8000/auth/user/2
Content-Type: application/json






