### Login usuario
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
    
    "email": "moreno@gmail.com",
    "password": "123456"
}

### Crear usuario
POST http://127.0.0.1:8000/user
Content-Type: application/json

{
    "nombre": "manuel",
    "email": "test@test.com",
    "password": "123456"
}

### Ver usuarios
GET  http://127.0.0.1:8000/view_user
Content-Type: application/json


### Status 
GET http://127.0.0.1:8000/status
Content-Type: application/json

### Limpiar Puertos de los Switches
POST http://127.0.0.1:8000/limpiar_ports
Accept: application/json


### Limpiar Puertos de los Switches por ip
POST http://127.0.0.1:8000/limpiar_ports/10.20.100.41
Accept: application/json

### Limpiar Puertos de los Switches y Guardar en DB
POST http://127.0.0.1:8000/registrar_ports_db
Content-Type: application/json

{
    "ip": "192.168.1.15",
    "nombre": "Puerto_Switch_01",
    "user_ip": "admin",
    "pass_ip": "secreto123",
    "description": "Limpieza de mantenimiento mensual"
}

### Ver Puertos Limpiados en DB
GET http://127.0.0.1:8000/view_clearports
Content-Type: application/json

